adding security context and network policies manifests

diff --git a/securitycontext-networkpolicy/intro/manifests/Deployment/loadgenerator.yaml b/securitycontext-networkpolicy/intro/manifests/Deployment/loadgenerator.yaml
--- a/securitycontext-networkpolicy/intro/manifests/Deployment/loadgenerator.yaml
+++ b/securitycontext-networkpolicy/intro/manifests/Deployment/loadgenerator.yaml
@@ -20,7 +20,7 @@ spec:
           value: frontend:80
         - name: USERS
           value: "10"
-        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.1.4
+        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.6
         name: main
         resources:
           limits:
@@ -29,5 +29,22 @@ spec:
           requests:
             cpu: 300m
             memory: 256Mi
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        env:
+        - name: FRONTEND_ADDR
+          value: frontend:80
+        image: busybox:latest
+        name: frontend-check
       restartPolicy: Always
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
diff --git a/securitycontext-networkpolicy/kubernetes-manifests.yaml b/securitycontext-networkpolicy/kubernetes-manifests.yaml
--- a/securitycontext-networkpolicy/kubernetes-manifests.yaml
+++ b/securitycontext-networkpolicy/kubernetes-manifests.yaml
@@ -29,10 +29,11 @@ spec:
       labels:
         app: emailservice
     spec:
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/emailservice:v0.1.4
+        image: gcr.io/google-samples/microservices-demo/emailservice:v0.3.6
         ports:
         - containerPort: 8080
         env:
@@ -84,9 +85,10 @@ spec:
       labels:
         app: checkoutservice
     spec:
+      serviceAccountName: default
       containers:
         - name: server
-          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.1.4
+          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.3.6
           ports:
           - containerPort: 5050
           readinessProbe:
@@ -152,10 +154,11 @@ spec:
       labels:
         app: recommendationservice
     spec:
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.1.4
+        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.3.6
         ports:
         - containerPort: 8080
         readinessProbe:
@@ -213,9 +216,10 @@ spec:
       annotations:
         sidecar.istio.io/rewriteAppHTTPProbers: "true"
     spec:
+      serviceAccountName: default
       containers:
         - name: server
-          image: gcr.io/google-samples/microservices-demo/frontend:v0.1.4
+          image: gcr.io/google-samples/microservices-demo/frontend:v0.3.6
           ports:
           - containerPort: 8080
           readinessProbe:
@@ -251,12 +255,18 @@ spec:
             value: "checkoutservice:5050"
           - name: AD_SERVICE_ADDR
             value: "adservice:9555"
+          # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
+          # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp 
+          # - name: ENV_PLATFORM 
+          #   value: "aws"
           - name: DISABLE_TRACING
             value: "1"
           - name: DISABLE_PROFILER
             value: "1"
           # - name: JAEGER_SERVICE_ADDR
           #   value: "jaeger-collector:14268"
+          # - name: CYMBAL_BRANDING
+          #   value: "true"
           resources:
             requests:
               cpu: 100m
@@ -304,15 +314,22 @@ spec:
       labels:
         app: paymentservice
     spec:
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.1.4
+        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.3.6
         ports:
         - containerPort: 50051
         env:
         - name: PORT
           value: "50051"
+        - name: DISABLE_TRACING
+          value: "1"
+        - name: DISABLE_PROFILER
+          value: "1"
+        - name: DISABLE_DEBUGGER
+          value: "1"
         readinessProbe:
           exec:
             command: ["/bin/grpc_health_probe", "-addr=:50051"]
@@ -353,10 +370,11 @@ spec:
       labels:
         app: productcatalogservice
     spec:
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.1.4
+        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.3.6
         ports:
         - containerPort: 3550
         env:
@@ -410,19 +428,16 @@ spec:
       labels:
         app: cartservice
     spec:
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/cartservice:v0.1.4
+        image: gcr.io/google-samples/microservices-demo/cartservice:v0.3.6
         ports:
         - containerPort: 7070
         env:
         - name: REDIS_ADDR
           value: "redis-cart:6379"
-        - name: PORT
-          value: "7070"
-        - name: LISTEN_ADDR
-          value: "0.0.0.0"
         resources:
           requests:
             cpu: 200m
@@ -469,11 +484,28 @@ spec:
       annotations:
         sidecar.istio.io/rewriteAppHTTPProbers: "true"
     spec:
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
       restartPolicy: Always
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        name: frontend-check
+        image: busybox:latest
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
       containers:
       - name: main
-        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.1.4
+        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.6
         env:
         - name: FRONTEND_ADDR
           value: "frontend:80"
@@ -500,10 +532,11 @@ spec:
       labels:
         app: currencyservice
     spec:
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.1.4
+        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.3.6
         ports:
         - name: grpc
           containerPort: 7000
@@ -556,9 +589,10 @@ spec:
       labels:
         app: shippingservice
     spec:
+      serviceAccountName: default
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.1.4
+        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.3.6
         ports:
         - containerPort: 50051
         env:
@@ -570,8 +604,8 @@ spec:
           value: "1"
         - name: DISABLE_PROFILER
           value: "1"
-        ##- name: JAEGER_SERVICE_ADDR
-        #  value: "jaeger-collector:14268"
+        # - name: JAEGER_SERVICE_ADDR
+        #   value: "jaeger-collector:14268"
         readinessProbe:
           periodSeconds: 5
           exec:
@@ -666,11 +700,11 @@ spec:
       labels:
         app: adservice
     spec:
+      serviceAccountName: default
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-#        image: gcr.io/google-samples/microservices-demo/adservice #:v1.0.81
-        image: rookout/microservices-demo-adservice #:v1.0.81
+        image: gcr.io/google-samples/microservices-demo/adservice:v0.3.6
         ports:
         - containerPort: 9555
         env:
@@ -681,7 +715,7 @@ spec:
         - name: DISABLE_TRACING
           value: "1"
         # - name: JAEGER_SERVICE_ADDR
-        #  value: "jaeger-collector:14268"
+        #   value: "jaeger-collector:14268"
         resources:
           requests:
             cpu: 200m
@@ -712,3 +746,4 @@ spec:
   - name: grpc
     port: 9555
     targetPort: 9555
+---
diff --git a/securitycontext-networkpolicy/outro/manifests/Deployment/loadgenerator.yaml b/securitycontext-networkpolicy/outro/manifests/Deployment/loadgenerator.yaml
--- a/securitycontext-networkpolicy/outro/manifests/Deployment/loadgenerator.yaml
+++ b/securitycontext-networkpolicy/outro/manifests/Deployment/loadgenerator.yaml
@@ -15,6 +15,7 @@ spec:
         app: loadgenerator
     spec:
       securityContext:
+        runAsNonRoot: true
         runAsUser: 1000
       containers:
       - env:
@@ -22,8 +23,15 @@ spec:
           value: frontend:80
         - name: USERS
           value: "10"
-        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.1.4
+        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.6
         imagePullPolicy: Always
+        securityContext:
+          runAsNonRoot: true
+          readOnlyRootFilesystem: true
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - all  
         name: main
         resources:
           limits:
@@ -32,22 +40,32 @@ spec:
           requests:
             cpu: 300m
             memory: 256Mi
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        env:
+        - name: FRONTEND_ADDR
+          value: frontend:80
+        image: docker.io/busybox:1.34.1
+        name: frontend-check
+        imagePullPolicy: Always
+
         securityContext:
           runAsNonRoot: true
-          readOnlyRootFilesystem: true
+          readOnlyRootFilesystem: false
           allowPrivilegeEscalation: false
           capabilities:
             drop:
-              - all
-
+              - all  
       restartPolicy: Always
-
-
-#        securityContext:
-#        #  runAsNonRoot: true 
-#          readOnlyRootFilesystem: true
-#          allowPrivilegeEscalation: false
-#          capabilities:
-#            drop:
-#              - all
+      serviceAccountName: default
+      automountServiceAccountToken: true
       terminationGracePeriodSeconds: 5
